# Generated by Django 4.2.3 on 2023-07-14 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('size', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=80)),
                ('stock_number', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
    ]
