# Generated by Django 4.2.3 on 2023-07-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='rgb_color',
            new_name='rgb',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
