# Generated by Django 4.2.3 on 2023-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_color_name_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
