# Generated by Django 4.2.3 on 2023-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.CharField(max_length=20),
        ),
    ]
