# Generated by Django 4.2.3 on 2023-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_color_name_alter_color_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'm'), ('X', 'x'), ('XX', 'xx'), ('XXX', 'xxx'), ('XL', 'xl')], default='M', max_length=5),
        ),
    ]
